language: java
jdk:
- oraclejdk7
before_install: git clone -b travis `git config --get remote.origin.url`
script: mvn clean deploy --settings settings.xml
notifications:
  email: false
env:
  global:
  - secure: "Cy0T7gOU3eVi+EsB5hefoOoJm/qzq4GsZpvbGViLDqgcGXotITuaXh318HBfrbM6DRni7i5xJ4CViMm0tycWBTxSER0oNg1x1f5t0lV3v60MX/TLE9wg/ZD9Ax7cTiK6evPucCQHJvkvonVHhzTYeeftoGD8d/BsD5Knm5I+5KA="
  - secure: "HMeTEEx1HQ+BTLZboxl5WQdR2Xiz6fVtVd4SV0THdRrOfNAJ6YPgketXSFtg8RQj0/senuQth/zl/pqz+CbucBYJL3sSdtUAyp4Txsauny1YwA1gMdNT+uO1E9gdSXCoELpBXD6EFR9V8wnRG7eUJ2UNQzF8ME0X6+qQ5CkXEOY="
